// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: fraud.proto

package fraud

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FraudCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	FromAccount   string                 `protobuf:"bytes,2,opt,name=from_account,json=fromAccount,proto3" json:"from_account,omitempty"`
	ToAccount     string                 `protobuf:"bytes,3,opt,name=to_account,json=toAccount,proto3" json:"to_account,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	DeviceId      string                 `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	IpAddress     string                 `protobuf:"bytes,6,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FraudCheckRequest) Reset() {
	*x = FraudCheckRequest{}
	mi := &file_fraud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudCheckRequest) ProtoMessage() {}

func (x *FraudCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fraud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudCheckRequest.ProtoReflect.Descriptor instead.
func (*FraudCheckRequest) Descriptor() ([]byte, []int) {
	return file_fraud_proto_rawDescGZIP(), []int{0}
}

func (x *FraudCheckRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *FraudCheckRequest) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *FraudCheckRequest) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *FraudCheckRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *FraudCheckRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *FraudCheckRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type FraudCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verdict       string                 `protobuf:"bytes,1,opt,name=verdict,proto3" json:"verdict,omitempty"` // "ALLOW" | "BLOCK"
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`   // 0.0-1.0, informational
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`   // e.g. "amount_over_threshold", "velocity", ""
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FraudCheckResponse) Reset() {
	*x = FraudCheckResponse{}
	mi := &file_fraud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudCheckResponse) ProtoMessage() {}

func (x *FraudCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fraud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudCheckResponse.ProtoReflect.Descriptor instead.
func (*FraudCheckResponse) Descriptor() ([]byte, []int) {
	return file_fraud_proto_rawDescGZIP(), []int{1}
}

func (x *FraudCheckResponse) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *FraudCheckResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *FraudCheckResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_fraud_proto protoreflect.FileDescriptor

const file_fraud_proto_rawDesc = "" +
	"\n" +
	"\vfraud.proto\x12\x05fraud\"\xd0\x01\n" +
	"\x11FraudCheckRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12!\n" +
	"\ffrom_account\x18\x02 \x01(\tR\vfromAccount\x12\x1d\n" +
	"\n" +
	"to_account\x18\x03 \x01(\tR\ttoAccount\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1b\n" +
	"\tdevice_id\x18\x05 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x06 \x01(\tR\tipAddress\"\\\n" +
	"\x12FraudCheckResponse\x12\x18\n" +
	"\averdict\x18\x01 \x01(\tR\averdict\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason2T\n" +
	"\fFraudService\x12D\n" +
	"\rCheckTransfer\x12\x18.fraud.FraudCheckRequest\x1a\x19.fraud.FraudCheckResponseBV\n" +
	"\x14com.aegis.fraud.grpcZ>github.com/aegis-banking/fraud-service/internal/pb/fraud;fraudb\x06proto3"

var (
	file_fraud_proto_rawDescOnce sync.Once
	file_fraud_proto_rawDescData []byte
)

func file_fraud_proto_rawDescGZIP() []byte {
	file_fraud_proto_rawDescOnce.Do(func() {
		file_fraud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fraud_proto_rawDesc), len(file_fraud_proto_rawDesc)))
	})
	return file_fraud_proto_rawDescData
}

var file_fraud_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fraud_proto_goTypes = []any{
	(*FraudCheckRequest)(nil),  // 0: fraud.FraudCheckRequest
	(*FraudCheckResponse)(nil), // 1: fraud.FraudCheckResponse
}
var file_fraud_proto_depIdxs = []int32{
	0, // 0: fraud.FraudService.CheckTransfer:input_type -> fraud.FraudCheckRequest
	1, // 1: fraud.FraudService.CheckTransfer:output_type -> fraud.FraudCheckResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fraud_proto_init() }
func file_fraud_proto_init() {
	if File_fraud_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fraud_proto_rawDesc), len(file_fraud_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fraud_proto_goTypes,
		DependencyIndexes: file_fraud_proto_depIdxs,
		MessageInfos:      file_fraud_proto_msgTypes,
	}.Build()
	File_fraud_proto = out.File
	file_fraud_proto_goTypes = nil
	file_fraud_proto_depIdxs = nil
}
