input {
    rabbitmq {
        host => "rabbitmq"
        port => 5672
        user => "${RABBITMQ_USER}"
        password => "${RABBITMQ_PASSWORD}"
        queue => "audit_queue"
        durable => true
        codec => "json"
    }
}

filter {
    mutate {
        add_field => {
            "log_source" => "aegis-audit-pipeline"
            "environment" => "development"
        }
    }

    date {
        match => ["timestamp", "ISO8601"]
    }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "aegis-audit-logs-%{+YYYY.MM.dd}"
    user => "${ELASTICSEARCH_USER:-}"
    password => "${ELASTICSEARCH_PASSWORD:-}"
  }
  stdout { 
    codec => rubydebug 
  }
}
